import { Room, TimeSlot } from '../types';
import { INITIAL_USER } from './accounts';

export { INITIAL_USER };

export const TODAY_STR = (() => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
})();

const tomorrow = new Date();
tomorrow.setDate(tomorrow.getDate() + 1);
export const TOMORROW_STR = `${tomorrow.getFullYear()}-${String(tomorrow.getMonth() + 1).padStart(2, '0')}-${String(tomorrow.getDate()).padStart(2, '0')}`;

export const STANDARD_SLOTS: Omit<TimeSlot, 'status' | 'bookedBy' | 'purpose'>[] = [
  { id: 'slot-1', startTime: '07:30', endTime: '09:30', label: 'Ca 1 (07:30 - 09:30)' },
  { id: 'slot-2', startTime: '09:45', endTime: '11:45', label: 'Ca 2 (09:45 - 11:45)' },
  { id: 'slot-3', startTime: '13:00', endTime: '15:00', label: 'Ca 3 (13:00 - 15:00)' },
  { id: 'slot-4', startTime: '15:15', endTime: '17:15', label: 'Ca 4 (15:15 - 17:15)' },
  { id: 'slot-5', startTime: '17:30', endTime: '19:30', label: 'Ca 5 (17:30 - 19:30)' },
  { id: 'slot-6', startTime: '19:45', endTime: '21:45', label: 'Ca 6 (19:45 - 21:45)' },
];

function generateSlotsForRoom(occupiedSlotIndices: number[] = []): Record<string, TimeSlot[]> {
  const buildSlots = (indices: number[]) =>
    STANDARD_SLOTS.map((slot, index) => {
      const isOccupied = indices.includes(index);
      return {
        ...slot,
        status: (isOccupied ? 'occupied' : 'available') as 'available' | 'occupied',
        bookedBy: isOccupied ? 'SV. Trần Đình Nam (21IT045)' : undefined,
        purpose: isOccupied ? 'Nghiên cứu khoa học & Đồ án tốt nghiệp' : undefined,
      };
    });

  return {
    [TODAY_STR]: buildSlots(occupiedSlotIndices),
    [TOMORROW_STR]: buildSlots(occupiedSlotIndices.map((i) => (i + 1) % 6)),
  };
}

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-1',
    name: 'Lab A3-101',
    building: 'Khu A - Tòa A3 (Tầng 1)',
    buildingCode: 'Building A',
    capacity: 40,
    type: 'lab',
    status: 'available',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng thực hành chuyên đề Cloud Computing và Mạng máy tính. Trang bị 40 máy trạm Dell Optiplex Core i7, switch Cisco, hệ thống điều hòa kép.',
    amenities: ['40 Máy trạm Core i7', 'Điều hòa 2 chiều', 'Máy chiếu 4K Laser', 'Bảng kính từ', 'WiFi 6 VKU-HighSpeed', 'Hệ thống Switch Cisco'],
    slots: generateSlotsForRoom([3]),
  },
  {
    id: 'room-2',
    name: 'Lab A3-205 AI & Robotics',
    building: 'Khu A - Tòa A3 (Tầng 2)',
    buildingCode: 'Building A',
    capacity: 25,
    type: 'lab',
    status: 'occupied',
    floor: 2,
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    description: 'Trung tâm nghiên cứu Trí tuệ nhân tạo và Robot thông minh. Máy trạm tích hợp GPU NVIDIA RTX 4090 phục vụ huấn luyện mô hình Deep Learning.',
    amenities: ['10x Máy trạm GPU RTX 4090', 'Bàn test Robot di động', 'Màn hình tương tác 85 inch', 'Điều hòa trung tâm', 'Cáp quang 1Gbps'],
    slots: generateSlotsForRoom([0, 1, 2, 4]),
  },
  {
    id: 'room-3',
    name: 'Thư viện Zone B - Silent Area',
    building: 'Thư viện Trung tâm VKU (Tầng 2)',
    buildingCode: 'Central Library',
    capacity: 60,
    type: 'library_quiet',
    status: 'available',
    floor: 2,
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&auto=format&fit=crop&q=80',
    description: 'Khu vực tự học yên tĩnh tuyệt đối tại thư viện. Bàn học cá nhân có vách ngăn, đèn LED bảo vệ thị lực và ổ cắm sạc độc lập tại từng vị trí.',
    amenities: ['Bàn học cá nhân chống ồn', 'Đèn bàn LED chống cận', 'Ổ cắm điện & Type-C', 'Không gian yên tĩnh', 'Máy lọc không khí'],
    slots: generateSlotsForRoom([2]),
  },
  {
    id: 'room-4',
    name: 'Hội trường C1 - Seminar Hall',
    building: 'Khu C - Tòa C1 (Tầng 1)',
    buildingCode: 'Building C',
    capacity: 120,
    type: 'seminar',
    status: 'available',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    description: 'Hội trường đa năng phục vụ bảo vệ đồ án, seminar công nghệ, hội thảo doanh nghiệp với dàn âm thanh vòm JBL và sân khấu thuyết trình hiện đại.',
    amenities: ['Hệ thống âm thanh hội trường JBL', 'Micro không dây', '2 Màn hình phụ LED', 'Bục diễn thuyết', 'Điều hòa công suất lớn'],
    slots: generateSlotsForRoom([0, 3]),
  },
  {
    id: 'room-5',
    name: 'VKU MakerSpace - IoT Lab',
    building: 'Khu Đổi mới Sáng tạo - Tòa V (Tầng 1)',
    buildingCode: 'Innovation Hub',
    capacity: 35,
    type: 'makerspace',
    status: 'available',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian sáng tạo cho kỹ sư phần cứng và IoT. Cung cấp máy in 3D, máy cắt laser, kit vi điều khiển ESP32, STM32, Arduino và trạm hàn an toàn.',
    amenities: ['3 Máy in 3D Bambu Lab', 'Kit vi điều khiển IoT', 'Máy hiện sóng dao động', 'Trạm hàn thiếc an toàn', 'Bàn làm việc nhóm lớn'],
    slots: generateSlotsForRoom([1, 4]),
  },
  {
    id: 'room-6',
    name: 'Smart Classroom C2-102',
    building: 'Khu C - Tòa C2 (Tầng 1)',
    buildingCode: 'Building C',
    capacity: 50,
    type: 'smart_classroom',
    status: 'available',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng học tương tác thông minh với bảng điện tử ViewSonic, camera AI tự động theo dõi giảng viên phục vụ lớp học kết hợp hybrid online-offline.',
    amenities: ['Bảng tương tác ViewSonic 75"', 'Camera PTZ theo dõi tự động', 'Micro trần định hướng', 'Bàn ghế linh hoạt ghép nhóm'],
    slots: generateSlotsForRoom([2, 5]),
  },
  {
    id: 'room-7',
    name: 'Lab A2-304 Mobile & Web Dev',
    building: 'Khu A - Tòa A2 (Tầng 3)',
    buildingCode: 'Building A',
    capacity: 45,
    type: 'lab',
    status: 'available',
    floor: 3,
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng lab chuyên sâu phát triển ứng dụng di động React Native, Flutter, iOS/Android. Cài đặt sẵn Android SDK, Xcode môi trường mô phỏng.',
    amenities: ['Máy trạm RAM 32GB', 'Cáp kết nối thiết bị di động test', 'Máy chiếu Full HD', 'Điều hòa 2 chiều', 'Mạng nội bộ Gigabit'],
    slots: generateSlotsForRoom([0, 1]),
  },
  {
    id: 'room-8',
    name: 'Thư viện - Thảo luận nhóm G1',
    building: 'Thư viện Trung tâm VKU (Tầng 1)',
    buildingCode: 'Central Library',
    capacity: 10,
    type: 'meeting',
    status: 'occupied',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng thảo luận nhóm cách âm tiêu chuẩn. Thích hợp họp nhóm đồ án, phỏng vấn thử, luyện thuyết trình với TV trình chiếu 55 inch.',
    amenities: ['TV 55" HDMI & AirPlay', 'Tường viết bút dạ', 'Bàn họp oval', 'Cách âm 80%', 'Điều hòa riêng biệt'],
    slots: generateSlotsForRoom([0, 1, 2, 3]),
  },
  {
    id: 'room-9',
    name: 'Thư viện - Thảo luận nhóm G2',
    building: 'Thư viện Trung tâm VKU (Tầng 1)',
    buildingCode: 'Central Library',
    capacity: 12,
    type: 'meeting',
    status: 'available',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng thảo luận nhóm quy mô 12 thành viên. Trang bị hệ thống hội nghị truyền hình trực tuyến Polycom và bảng trắng di động hai mặt.',
    amenities: ['Smart TV 65"', 'Webcam hội nghị Polycom', 'Bảng trắng di động', 'Bàn ghế chân xoay', 'Ổ cắm trung tâm'],
    slots: generateSlotsForRoom([3]),
  },
  {
    id: 'room-10',
    name: 'Lab Vi mạch Bán dẫn A1-102',
    building: 'Khu A - Tòa A1 (Tầng 1)',
    buildingCode: 'Building A',
    capacity: 30,
    type: 'lab',
    status: 'maintenance',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng thực hành thiết kế vi mạch chuyên sâu thuộc Trung tâm Công nghệ Bán dẫn VKU. Bộ công cụ EDA Cadence, Synopsys và board FPGA Xilinx.',
    amenities: ['Bộ máy trạm thiết kế EDA', 'FPGA Xilinx Vivado', 'Máy đo xung logic', 'Hệ thống phòng sạch lọc khí'],
    slots: generateSlotsForRoom([0, 2, 4]),
  },
  {
    id: 'room-11',
    name: 'Phòng Hội thảo Quốc tế V-201',
    building: 'Khu Đổi mới Sáng tạo - Tòa V (Tầng 2)',
    buildingCode: 'Innovation Hub',
    capacity: 80,
    type: 'seminar',
    status: 'available',
    floor: 2,
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng hội thảo đạt chuẩn đón tiếp đối tác quốc tế từ Hàn Quốc và thế giới. Trang bị cabin dịch song song 2 kênh và hệ thống ghi hình tự động.',
    amenities: ['Cabin dịch thuật 2 kênh', 'Hệ thống micro hội nghị đại biểu', 'Màn hình LED P2 200 inch', 'Ghế đệm bọc da cao cấp'],
    slots: generateSlotsForRoom([]),
  },
  {
    id: 'room-12',
    name: 'Smart Classroom C2-203',
    building: 'Khu C - Tòa C2 (Tầng 2)',
    buildingCode: 'Building C',
    capacity: 55,
    type: 'smart_classroom',
    status: 'available',
    floor: 2,
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng học lý thuyết hiện đại, hệ thống loa phân vùng âm thanh đồng đều và bàn ghế bánh xe cho phép chuyển đổi bố cục phòng trong 1 phút.',
    amenities: ['Máy chiếu siêu gần tương tác', 'Hệ thống âm thanh phân vùng', 'Bàn module xếp hình', 'Wifi chuyên dụng 100 người'],
    slots: generateSlotsForRoom([1]),
  },
  {
    id: 'room-13',
    name: 'CyberLab A3-301 An toàn Thông tin',
    building: 'Khu A - Tòa A3 (Tầng 3)',
    buildingCode: 'Building A',
    capacity: 35,
    type: 'lab',
    status: 'available',
    floor: 3,
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    description: 'Môi trường mô phỏng Cyber Range diễn tập tấn công & phòng thủ mạng. Tách biệt mạng cô lập, máy chủ ảo hóa VMware ESXi chuyên dụng.',
    amenities: ['Hệ thống mạng cô lập Sandbox', 'Máy chủ Cyber Range', 'Màn hình hiển thị bản đồ tấn công', 'Phần mềm Kali Linux trạm'],
    slots: generateSlotsForRoom([2, 3]),
  },
  {
    id: 'room-14',
    name: 'Studio E-Learning & Media V-305',
    building: 'Khu Đổi mới Sáng tạo - Tòa V (Tầng 3)',
    buildingCode: 'Innovation Hub',
    capacity: 8,
    type: 'studio',
    status: 'available',
    floor: 3,
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng ghi hình bài giảng số và podcast công nghệ. Hệ thống phông xanh, đèn studio softbox, mic thu âm Rode PodMic và máy quay 4K Sony.',
    amenities: ['Phông xanh Chromakey', 'Micro thu âm podcast Rode', 'Ánh sáng Studio chuyên nghiệp', 'Phần mềm dựng phim Premiere'],
    slots: generateSlotsForRoom([0, 4]),
  },
  {
    id: 'room-15',
    name: 'K-Zone Tự học 01 (Ký túc xá)',
    building: 'Khu Ký túc xá Sinh viên (Tầng 1)',
    buildingCode: 'Building K',
    capacity: 40,
    type: 'library_quiet',
    status: 'available',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian tự học 24/7 phục vụ sinh viên nội trú ký túc xá VKU. Nước uống tinh khiết miễn phí, bàn học có ổ cắm cá nhân và điều hòa cả đêm.',
    amenities: ['Mở cửa 24/7', 'Cây nước nóng lạnh', 'Bàn tự học có đèn', 'Bảo vệ túc trực an ninh', 'WiFi tốc độ cao'],
    slots: generateSlotsForRoom([]),
  },
  {
    id: 'room-16',
    name: 'K-Zone Tự học 02 (Ký túc xá)',
    building: 'Khu Ký túc xá Sinh viên (Tầng 2)',
    buildingCode: 'Building K',
    capacity: 35,
    type: 'library_quiet',
    status: 'available',
    floor: 2,
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng học yên tĩnh tầng 2 Ký túc xá, không gian thoáng đãng ngắm trọn sân thể thao VKU, ghế lười thư giãn cho các phiên đọc sách tập trung.',
    amenities: ['Ghế lười thư giãn', 'Bàn gỗ dài nhóm', 'Cửa kính view sân thể thao', 'Điều hòa không khí mát mẻ'],
    slots: generateSlotsForRoom([1, 2]),
  },
  {
    id: 'room-17',
    name: 'Coworking Lounge Sinh viên VKU',
    building: 'Thư viện Trung tâm VKU (Tầng 1)',
    buildingCode: 'Central Library',
    capacity: 75,
    type: 'makerspace',
    status: 'available',
    floor: 1,
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    description: 'Khu vực mở phong cách cafe khởi nghiệp dành cho sinh viên giao lưu, lên ý tưởng dự án Hackathon, thảo luận thoải mái không gò bó.',
    amenities: ['Quầy cafe tự phục vụ', 'Sofa & bàn gỗ dài', 'Bảng ý tưởng canvas khổng lồ', 'Khu vực sạc không dây'],
    slots: generateSlotsForRoom([0]),
  },
  {
    id: 'room-18',
    name: 'Lab A2-401 Đồ họa & Game Dev',
    building: 'Khu A - Tòa A2 (Tầng 4)',
    buildingCode: 'Building A',
    capacity: 35,
    type: 'lab',
    status: 'occupied',
    floor: 4,
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng lab chuyên ngành Thiết kế đồ họa và Công nghệ Game Unity/Unreal Engine. Màn hình chuẩn màu 100% sRGB và bảng vẽ Wacom Intuos.',
    amenities: ['35 Bảng vẽ điện tử Wacom', 'Màn hình Dell UltraSharp chuẩn màu', 'Card đồ họa RTX chuyên Game', 'Kính thực tế ảo VR Meta Quest 3'],
    slots: generateSlotsForRoom([0, 1, 2, 3, 4]),
  },
  {
    id: 'room-19',
    name: 'Phòng Hội nghị Khoa CNTT B1-201',
    building: 'Khu B - Tòa B1 (Tầng 2)',
    buildingCode: 'Building B',
    capacity: 30,
    type: 'meeting',
    status: 'available',
    floor: 2,
    image: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng họp chính thức của Khoa Khoa học Máy tính & Công nghệ Thông tin. Trang bị bàn hội nghị gỗ sồi cao cấp và micro cổ ngỗng từng ghế.',
    amenities: ['Hệ thống micro cổ ngỗng Bosch', 'Màn hình tương tác cảm ứng', 'Máy lọc nước văn phòng', 'Ghế đệm xoay công thái học'],
    slots: generateSlotsForRoom([3, 4]),
  },
  {
    id: 'room-20',
    name: 'Smart Classroom C1-204',
    building: 'Khu C - Tòa C1 (Tầng 2)',
    buildingCode: 'Building C',
    capacity: 45,
    type: 'smart_classroom',
    status: 'available',
    floor: 2,
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng học chuyên đề mạng máy tính và phát triển ứng dụng di động VKU với bảng viết xung quanh tường 360 độ.',
    amenities: ['Bảng viết tường 360 độ', 'Máy chiếu kép siêu nét', 'Hệ thống WiFi Mesh', 'Cửa sổ đón ánh sáng tự nhiên'],
    slots: generateSlotsForRoom([1]),
  },
  {
    id: 'room-21',
    name: 'Phòng Nghiên cứu Sau đại học V-401',
    building: 'Khu Đổi mới Sáng tạo - Tòa V (Tầng 4)',
    buildingCode: 'Innovation Hub',
    capacity: 20,
    type: 'seminar',
    status: 'available',
    floor: 4,
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian yên tĩnh dành riêng cho học viên thạc sĩ, nghiên cứu sinh và các nhóm lab trọng điểm của VKU làm việc chuyên sâu.',
    amenities: ['Bàn làm việc cá nhân có tủ khóa', 'Tủ sách chuyên khảo khoa học', 'Máy in laser & scan tốc độ cao', 'Phòng họp nội bộ nhỏ'],
    slots: generateSlotsForRoom([0]),
  },
  {
    id: 'room-22',
    name: 'Thư viện Khu B - Silent Zone 2',
    building: 'Thư viện Trung tâm VKU (Tầng 3)',
    buildingCode: 'Central Library',
    capacity: 50,
    type: 'library_quiet',
    status: 'available',
    floor: 3,
    image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop&q=80',
    description: 'Tầng 3 Thư viện dành riêng cho sinh viên đọc sách và ôn thi học kỳ. Không gian tràn ngập cây xanh, hệ thống khử ồn chủ động.',
    amenities: ['Hệ thống cách âm công nghệ cao', 'Khu vườn cây xanh lọc bụi', 'Bàn học cá nhân', 'Đèn chống cận thị chuẩn Quốc tế'],
    slots: generateSlotsForRoom([]),
  },
];

